#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start

sudo sh -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        return 200 \"Hello World!\";
    }
}" > /etc/nginx/sites-available/default'

service nginx restart
