#!/usr/bin/env bash
# install nginx server
# return a page that contains the string Hello World!

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
