#!/usr/bin/env bash
# configue laod balancer

sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy

config="
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 379315-web-01 54.89.27.238:80 check
    server 379315-web-02 52.91.125.190:80 check
"

echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo systemctl enable haproxy
sudo service haproxy restart
